# Generated by Django 4.2.6 on 2023-10-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_time',
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=10)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.workingday'),
            preserve_default=False,
        ),
    ]
