# Generated by Django 4.2.6 on 2023-10-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_timeslot_remove_schedule_schedule_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingday',
            old_name='role',
            new_name='shift',
        ),
    ]
