# Generated by Django 4.2.6 on 2023-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_workingday_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='is_vacation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
