# Generated by Django 4.2.6 on 2023-10-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_workingday_is_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingday',
            name='shift',
        ),
    ]
