# Generated by Django 4.2.6 on 2023-10-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_workingday_shift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together=set(),
        ),
    ]
